# Generated by Django 4.1.5 on 2023-05-14 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('intervention_id', models.IntegerField(primary_key=True, serialize=False)),
                ('time_initiated', models.DateTimeField()),
            ],
            options={
                'db_table': 'intervention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('istatus', models.IntegerField(db_column='iStatus', primary_key=True, serialize=False)),
                ('status', models.TextField()),
                ('updated_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityIntervention',
            fields=[
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Intervetions.intervention')),
            ],
            options={
                'db_table': 'community_intervention',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoliceIntevention',
            fields=[
                ('intervention', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Intervetions.intervention')),
            ],
            options={
                'db_table': 'police_intevention',
                'managed': False,
            },
        ),
    ]
