# Generated by Django 4.1.5 on 2023-05-14 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('cid', models.OneToOneField(db_column='cid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='User.user')),
                ('occupation', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'citizen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.IntegerField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=30)),
                ('comm_name', models.CharField(max_length=35)),
                ('area', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'community',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('hhid', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField()),
                ('hh_name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'household',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Housemember',
            fields=[
                ('hm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'housemember',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField()),
                ('left_on', models.DateTimeField(blank=True, null=True)),
                ('citizen_typ', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommunityLeader',
            fields=[
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Community.member')),
                ('elected_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'community_leader',
                'managed': False,
            },
        ),
    ]
